parameters:
    mopa_feed.message_manager.class: Mopa\Bundle\FeedBundle\Model\MessageManager

services:
    mopa_feed.message_manager:
        class: %mopa_feed.message_manager.class%
        arguments:
            - @old_sound_rabbit_mq.websockets_producer
            - @doctrine.orm.entity_manager
            - @jms_serializer
            - @mopa_feed.message_helper
            - %mopa_feed.message.class%
