parameters:
    mopa_feed.message_helper.class: Mopa\Bundle\FeedBundle\Model\MessageHelper

services:
    P2\Bundle\RatchetBundle\WebSocket\Server\Factory:
        alias: p2_ratchet.websocket.server_factory

    Mopa\Bundle\FeedBundle\Command\WebsocketServerCommand:
        public: true
        autowire: true
        tags:
            - {name: console.command}
    mopa_feed.message_helper:
        class: "%mopa_feed.message_helper.class%"
        lazy: true
        arguments:
            - "@service_container"
            - "%mopa_feed.message.template_prefix%"
            - "@logger"
        tags:
            - { name: monolog.logger, channel: 'mopa_feed.message_helper'}

    mopa_feed.encryption_helper:
        class: Mopa\Bundle\FeedBundle\WebSocket\Server\EncryptionHelper
        arguments:
            - "%kernel.cache_dir%"

    mopa_feed.twig.extension:
        class: Mopa\Bundle\FeedBundle\Twig\FeedExtension
        arguments:
            - "@mopa_feed.encryption_helper"
        tags:
            - { name: twig.extension }

    Mopa\Bundle\FeedBundle\WebSocket\Server\ReactHelper:
        class: Mopa\Bundle\FeedBundle\WebSocket\Server\ReactHelper
