parameters:
    mopa_feed.message_helper.class: Mopa\Bundle\FeedBundle\Model\MessageHelper

services:
    mopa_feed.message_helper:
        class: %mopa_feed.message_helper.class%
        arguments:
            - @service_container
            - %mopa_feed.message.template_prefix%
