parameters:
#    mopa_feed.example.class: Mopa\Bundle\FeedBundle\Example

services:
#    mopa_feed.example:
#        class: %mopa_feed.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
