Mopa\Bundle\FeedBundle\Document\Message:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: string
            groups: ["mopa_feed_websockets", "mopa_feed_websockets.internal"]