Mopa\Bundle\FeedBundle\Entity\Message:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
            groups: ["mopa_feed_websockets", "mopa_feed_websockets.internal"]